language: r
warnings_are_errors: false
sudo: false
cache: packages
r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls()'
  - test $TRAVIS_BRANCH = "master" && test $TRAVIS_PULL_REQUEST = "false" && ./.push_gh_pages.sh
